-- Review supabase_security_audit.sql first. Applies only to this app's two tables.
-- Does not delete financial rows, users, or unrelated policies.
begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  created_at timestamptz not null default now()
);

create table if not exists public.financial_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.financial_data enable row level security;

-- Remove client roles' broad/default privileges. The app needs upsert and select only.
revoke all on table public.profiles from PUBLIC, anon, authenticated;
revoke all on table public.financial_data from PUBLIC, anon, authenticated;
-- Grant only the columns used by this app, including upsert's ownership key.
grant select (id,email,name), insert (id,email,name), update (id,email,name)
  on table public.profiles to authenticated;
grant select (id,user_id,data,updated_at), insert (user_id,data,updated_at), update (user_id,data,updated_at)
  on table public.financial_data to authenticated;

-- Covers legacy serial schemas as well as identity columns without granting read access.
do $$
declare sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.financial_data','id');
  if sequence_name is not null then
    execute format('revoke all on sequence %s from PUBLIC, anon, authenticated', sequence_name);
    execute format('grant usage on sequence %s to authenticated', sequence_name);
  end if;
end;
$$;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
drop policy if exists financial_select_own on public.financial_data;
drop policy if exists financial_insert_own on public.financial_data;
drop policy if exists financial_update_own on public.financial_data;
drop policy if exists financial_delete_own on public.financial_data;

create policy profiles_select_own on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy profiles_insert_own on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy financial_select_own on public.financial_data for select to authenticated
  using ((select auth.uid()) = user_id);
create policy financial_insert_own on public.financial_data for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy financial_update_own on public.financial_data for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Restrictive policies AND with existing permissive policies: an old USING(true)
-- cannot broaden ownership access. Keep unrelated policies for review instead of deleting them.
drop policy if exists profiles_owner_guard on public.profiles;
drop policy if exists financial_owner_guard on public.financial_data;
create policy profiles_owner_guard on public.profiles as restrictive for all to public
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy financial_owner_guard on public.financial_data as restrictive for all to public
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Server-controlled metadata; incoming client updated_at values are ignored.
create or replace function public.orgfinan_set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$$;
revoke all on function public.orgfinan_set_updated_at() from PUBLIC, anon, authenticated;
drop trigger if exists orgfinan_updated_at on public.financial_data;
create trigger orgfinan_updated_at before insert or update on public.financial_data
  for each row execute function public.orgfinan_set_updated_at();

-- Validate new writes without silently rewriting legacy rows.
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid='public.financial_data'::regclass and conname='financial_data_object') then
    alter table public.financial_data add constraint financial_data_object
      check (jsonb_typeof(data) = 'object') not valid;
  end if;
end;
$$;

commit;
