-- Minhas Finanças V4 - verificação da estrutura Supabase
-- Pode executar mais de uma vez.

create table if not exists public.financial_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.financial_data enable row level security;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.financial_data to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "financial_select_own" on public.financial_data;
drop policy if exists "financial_insert_own" on public.financial_data;
drop policy if exists "financial_update_own" on public.financial_data;
drop policy if exists "financial_delete_own" on public.financial_data;

create policy "profiles_select_own"
on public.profiles for select to authenticated
using (auth.uid() = id);

create policy "profiles_insert_own"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "financial_select_own"
on public.financial_data for select to authenticated
using (auth.uid() = user_id);

create policy "financial_insert_own"
on public.financial_data for insert to authenticated
with check (auth.uid() = user_id);

create policy "financial_update_own"
on public.financial_data for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "financial_delete_own"
on public.financial_data for delete to authenticated
using (auth.uid() = user_id);
